{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3da6780b-f065-4751-9b02-33e8f48e8a54",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x221d9b79640>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from pathlib import Path\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime as dt\n",
    "import matplotlib.pyplot as plt\n",
    "import arabic_reshaper\n",
    "from bidi.algorithm import get_display\n",
    "from IPython.display import HTML\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "import dash\n",
    "from dash import Dash,dcc,html, Input, Output\n",
    "\n",
    "BASE_DIR = Path().resolve().parent\n",
    "DATA_PATH = BASE_DIR / \"data\" / \"fix13.xlsx\"\n",
    "\n",
    "dfs = pd.read_excel(DATA_PATH, engine=\"openpyxl\", sheet_name=None)\n",
    "df =dfs[\"Sheet1\"]\n",
    "df2 =dfs[\"Sheet2\"]\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# تمیز کردن اسم ستون‌ها\n",
    "# =====================================================\n",
    "df.columns = df.columns.str.strip()\n",
    "\n",
    "# =====================================================\n",
    "# تغییر نام ستون‌ها\n",
    "# =====================================================\n",
    "df = df.rename(columns={\n",
    "\n",
    "    \"میزان نقدشوندگی\": \"نقدشوندگی\"\n",
    "\n",
    "})\n",
    "\n",
    "# =====================================================\n",
    "# تمیز کردن ستون نماد\n",
    "# =====================================================\n",
    "df[\"نماد\"] = (\n",
    "    df[\"نماد\"]\n",
    "    .astype(str)\n",
    "    .str.strip()\n",
    ")\n",
    "\n",
    "# =====================================================\n",
    "# تبدیل اعداد فارسی به انگلیسی\n",
    "# =====================================================\n",
    "persian_digits = '۰۱۲۳۴۵۶۷۸۹'\n",
    "english_digits = '0123456789'\n",
    "\n",
    "trans = str.maketrans(\n",
    "\n",
    "    persian_digits,\n",
    "\n",
    "    english_digits\n",
    ")\n",
    "\n",
    "# =====================================================\n",
    "# تابع تمیزسازی ستون‌های عددی\n",
    "# =====================================================\n",
    "def clean_numeric(col):\n",
    "\n",
    "    return pd.to_numeric(\n",
    "\n",
    "        col.astype(str)\n",
    "\n",
    "        .str.translate(trans)\n",
    "\n",
    "        .str.replace('٬', '', regex=False)\n",
    "\n",
    "        .str.replace('٫', '.', regex=False)\n",
    "\n",
    "        .str.replace('%', '', regex=False)\n",
    "\n",
    "        .str.replace(',', '', regex=False)\n",
    "\n",
    "        .str.strip(),\n",
    "\n",
    "        errors='coerce'\n",
    "    )\n",
    "\n",
    "# =====================================================\n",
    "# ستون‌های عددی\n",
    "# =====================================================\n",
    "numeric_cols = [\n",
    "\n",
    "    \"قیمت پایانی\",\n",
    "\n",
    "    \"حجم\",\n",
    "\n",
    "    \"ارزش معاملات\",\n",
    "\n",
    "    \"nav ابطال\",\n",
    "\n",
    "    \"بازدهی nav\",\n",
    "\n",
    "    \"AUM\",\n",
    "\n",
    "    \"بازدهی قیمتی\",\n",
    "\n",
    "    \"نقدشوندگی\",\n",
    "\n",
    "    \"ذخیره سود\"\n",
    "]\n",
    "\n",
    "for col in numeric_cols:\n",
    "\n",
    "    if col in df.columns:\n",
    "\n",
    "        df[col] = clean_numeric(df[col])\n",
    "\n",
    "# =====================================================\n",
    "# ستون‌های درصدی\n",
    "# =====================================================\n",
    "percent_columns = [\n",
    "\n",
    "    \"بازدهی قیمتی\",\n",
    "\n",
    "    \"بازدهی nav\",\n",
    "\n",
    "    \"نقدشوندگی\",\n",
    "\n",
    "    \"ذخیره سود\"\n",
    "]\n",
    "\n",
    "# =====================================================\n",
    "# لیست صندوق‌ها\n",
    "# =====================================================\n",
    "symbols = sorted(\n",
    "\n",
    "    df[\"نماد\"]\n",
    "\n",
    "    .dropna()\n",
    "\n",
    "    .unique()\n",
    ")\n",
    "\n",
    "# =====================================================\n",
    "# ساخت اپ\n",
    "# =====================================================\n",
    "app = Dash(__name__)\n",
    "\n",
    "server = app.server\n",
    "\n",
    "# =====================================================\n",
    "# Layout\n",
    "# =====================================================\n",
    "app.layout = html.Div([\n",
    "\n",
    "    # =================================================\n",
    "    # عنوان\n",
    "    # =================================================\n",
    "    html.H1(\n",
    "\n",
    "        \"📈 داشبورد صندوق‌های درآمدثابت\",\n",
    "\n",
    "        style={\n",
    "\n",
    "            'textAlign': 'center',\n",
    "\n",
    "            'marginBottom': '30px',\n",
    "\n",
    "            'color': '#1f2937'\n",
    "        }\n",
    "    ),\n",
    "\n",
    "    # =================================================\n",
    "    # Dropdown ها\n",
    "    # =================================================\n",
    "    html.Div([\n",
    "\n",
    "        # =============================================\n",
    "        # صندوق اول\n",
    "        # =============================================\n",
    "        html.Div([\n",
    "\n",
    "            html.Label(\n",
    "\n",
    "                \"صندوق اول\",\n",
    "\n",
    "                style={\n",
    "\n",
    "                    'fontWeight': 'bold',\n",
    "\n",
    "                    'marginBottom': '10px'\n",
    "                }\n",
    "            ),\n",
    "\n",
    "            dcc.Dropdown(\n",
    "\n",
    "                id='fund1',\n",
    "\n",
    "                options=[\n",
    "\n",
    "                    {\n",
    "                        'label': s,\n",
    "                        'value': s\n",
    "                    }\n",
    "\n",
    "                    for s in symbols\n",
    "                ],\n",
    "\n",
    "                value=symbols[0],\n",
    "\n",
    "                clearable=False\n",
    "\n",
    "            )\n",
    "\n",
    "        ],\n",
    "        style={\n",
    "\n",
    "            'width': '45%',\n",
    "\n",
    "            'display': 'inline-block'\n",
    "        }),\n",
    "\n",
    "        # =============================================\n",
    "        # صندوق دوم\n",
    "        #\n",
    "\n",
    "        html.Div([\n",
    "\n",
    "            html.Label(\n",
    "\n",
    "                \"صندوق دوم\",\n",
    "\n",
    "                style={\n",
    "\n",
    "                    'fontWeight': 'bold',\n",
    "\n",
    "                    'marginBottom': '10px'\n",
    "                }\n",
    "            ),\n",
    "\n",
    "            dcc.Dropdown(\n",
    "\n",
    "                id='fund2',\n",
    "\n",
    "                options=[\n",
    "\n",
    "                    {\n",
    "                        'label': s,\n",
    "                        'value': s\n",
    "                    }\n",
    "\n",
    "                    for s in symbols\n",
    "                ],\n",
    "\n",
    "                value=symbols[1],\n",
    "\n",
    "                clearable=False\n",
    "\n",
    "            )\n",
    "\n",
    "        ],\n",
    "        style={\n",
    "\n",
    "            'width': '45%',\n",
    "\n",
    "            'display': 'inline-block',\n",
    "\n",
    "            'float': 'right'\n",
    "        })\n",
    "\n",
    "    ]),\n",
    "\n",
    "    html.Br(),\n",
    "\n",
    "    # =================================================\n",
    "    # Tabs\n",
    "    # =================================================\n",
    "    dcc.Tabs(\n",
    "\n",
    "        id='tabs',\n",
    "\n",
    "        value='price-return-tab',\n",
    "\n",
    "        children=[\n",
    "\n",
    "            # =========================================\n",
    "            # بازدهی قیمتی\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='بازدهی قیمتی',\n",
    "\n",
    "                value='price-return-tab'\n",
    "            ),\n",
    "\n",
    "            # =========================================\n",
    "            # بازدهی NAV\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='بازدهی NAV',\n",
    "\n",
    "                value='nav-return-tab'\n",
    "            ),\n",
    "\n",
    "            # =========================================\n",
    "            # نقدشوندگی\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='نقدشوندگی',\n",
    "\n",
    "                value='liquidity-tab'\n",
    "            ),\n",
    "\n",
    "            # =========================================\n",
    "            # ذخیره سود\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='ذخیره سود',\n",
    "\n",
    "                value='reserve-tab'\n",
    "            ),\n",
    "\n",
    "            # =========================================\n",
    "            # AUM\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='AUM',\n",
    "\n",
    "                value='aum-tab'\n",
    "            ),\n",
    "\n",
    "            # =========================================\n",
    "            # ارزش معاملات\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='ارزش معاملات',\n",
    "\n",
    "                value='value-tab'\n",
    "            ),\n",
    "\n",
    "            # =========================================\n",
    "            # حجم معاملات\n",
    "            # =========================================\n",
    "            dcc.Tab(\n",
    "\n",
    "                label='حجم معاملات',\n",
    "\n",
    "                value='volume-tab'\n",
    "            )\n",
    "\n",
    "        ]\n",
    "    ),\n",
    "\n",
    "    html.Br(),\n",
    "\n",
    "    # =================================================\n",
    "    # نمودار اصلی\n",
    "    # =================================================\n",
    "    dcc.Graph(id='main-chart')\n",
    "\n",
    "],\n",
    "style={\n",
    "\n",
    "    'padding': '30px',\n",
    "\n",
    "    'fontFamily': 'Tahoma',\n",
    "\n",
    "    'backgroundColor': '#f3f4f6'\n",
    "}\n",
    ")\n",
    "\n",
    "# =====================================================\n",
    "# Callback اصلی\n",
    "# =====================================================\n",
    "@app.callback(\n",
    "\n",
    "    Output('main-chart', 'figure'),\n",
    "\n",
    "    [\n",
    "\n",
    "        Input('fund1', 'value'),\n",
    "\n",
    "        Input('fund2', 'value'),\n",
    "\n",
    "        Input('tabs', 'value')\n",
    "\n",
    "    ]\n",
    ")\n",
    "def update_chart(\n",
    "\n",
    "    fund1,\n",
    "\n",
    "    fund2,\n",
    "\n",
    "    selected_tab\n",
    "):\n",
    "\n",
    "    # =================================================\n",
    "    # فیلتر دیتا\n",
    "    # =================================================\n",
    "    dff = df[\n",
    "\n",
    "        df[\"نماد\"].isin([\n",
    "\n",
    "            fund1,\n",
    "\n",
    "            fund2\n",
    "        ])\n",
    "    ]\n",
    "\n",
    "    dff = dff.sort_values(\"تاریخ\")\n",
    "\n",
    "    # =================================================\n",
    "    # انتخاب ستون بر اساس تب\n",
    "    # =================================================\n",
    "    if selected_tab == 'price-return-tab':\n",
    "\n",
    "        y_col = \"بازدهی قیمتی\"\n",
    "\n",
    "        title = \"مقایسه بازدهی قیمتی\"\n",
    "\n",
    "    elif selected_tab == 'nav-return-tab':\n",
    "\n",
    "        y_col = \"بازدهی nav\"\n",
    "\n",
    "        title = \"مقایسه بازدهی NAV\"\n",
    "\n",
    "    elif selected_tab == 'liquidity-tab':\n",
    "\n",
    "        y_col = \"نقدشوندگی\"\n",
    "\n",
    "        title = \"مقایسه نقدشوندگی\"\n",
    "\n",
    "    elif selected_tab == 'reserve-tab':\n",
    "\n",
    "        y_col = \"ذخیره سود\"\n",
    "\n",
    "        title = \"مقایسه ذخیره سود\"\n",
    "\n",
    "    elif selected_tab == 'aum-tab':\n",
    "\n",
    "        y_col = \"AUM\"\n",
    "\n",
    "        title = \"مقایسه AUM\"\n",
    "\n",
    "    elif selected_tab == 'value-tab':\n",
    "\n",
    "        y_col = \"ارزش معاملات\"\n",
    "\n",
    "        title = \"مقایسه ارزش معاملات\"\n",
    "\n",
    "    elif selected_tab == 'volume-tab':\n",
    "\n",
    "        y_col = \"حجم\"\n",
    "\n",
    "        title = \"مقایسه حجم معاملات\"\n",
    "\n",
    "    # =================================================\n",
    "    # دیتای نمودار\n",
    "    # =================================================\n",
    "    plot_df = dff.copy()\n",
    "\n",
    "    # =================================================\n",
    "    # اگر ستون درصدی بود ×100 کن\n",
    "    # =================================================\n",
    "    if y_col in percent_columns:\n",
    "\n",
    "        plot_df[y_col] = plot_df[y_col] * 100\n",
    "\n",
    "    # =================================================\n",
    "    # نمودار\n",
    "    # =================================================\n",
    "    fig = px.line(\n",
    "\n",
    "        plot_df,\n",
    "\n",
    "        x='تاریخ',\n",
    "\n",
    "        y=y_col,\n",
    "\n",
    "        color='نماد',\n",
    "\n",
    "        markers=True,\n",
    "\n",
    "        title=title\n",
    "    )\n",
    "\n",
    "    # =================================================\n",
    "    # استایل نمودار\n",
    "    # =================================================\n",
    "    fig.update_layout(\n",
    "\n",
    "        hovermode='x unified',\n",
    "\n",
    "        title_font_size=24,\n",
    "\n",
    "        height=650,\n",
    "\n",
    "        plot_bgcolor='white',\n",
    "\n",
    "        paper_bgcolor='white',\n",
    "\n",
    "        legend_title='صندوق',\n",
    "\n",
    "        font=dict(\n",
    "\n",
    "            family='Tahoma',\n",
    "\n",
    "            size=14,\n",
    "\n",
    "            color='#111827'\n",
    "        ),\n",
    "\n",
    "        margin=dict(\n",
    "\n",
    "            l=40,\n",
    "\n",
    "            r=40,\n",
    "\n",
    "            t=80,\n",
    "\n",
    "            b=40\n",
    "        )\n",
    "    )\n",
    "\n",
    "    # =================================================\n",
    "    # استایل خطوط\n",
    "    # =================================================\n",
    "    fig.update_traces(\n",
    "\n",
    "        line=dict(width=3),\n",
    "\n",
    "        marker=dict(size=5)\n",
    "    )\n",
    "\n",
    "    # =================================================\n",
    "    # محور X\n",
    "    # =================================================\n",
    "    fig.update_xaxes(\n",
    "\n",
    "        showgrid=False,\n",
    "\n",
    "        tickangle=-45\n",
    "    )\n",
    "\n",
    "    # =================================================\n",
    "    # محور Y\n",
    "    # =================================================\n",
    "    fig.update_yaxes(\n",
    "\n",
    "        showgrid=True,\n",
    "\n",
    "        gridcolor='#e5e7eb'\n",
    "    )\n",
    "\n",
    "    # =================================================\n",
    "    # درصدی کردن محور Y\n",
    "    # =================================================\n",
    "    if y_col in percent_columns:\n",
    "\n",
    "        fig.update_yaxes(\n",
    "\n",
    "            ticksuffix=\"%\",\n",
    "\n",
    "            tickformat=\".1f\"\n",
    "        )\n",
    "\n",
    "    return fig\n",
    "\n",
    "# =====================================================\n",
    "# اجرای برنامه\n",
    "# =====================================================\n",
    "if __name__ == '__main__':\n",
    "\n",
    "    app.run(\n",
    "\n",
    "        debug=True,\n",
    "\n",
    "        port=8050\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cbba741b-dc7f-498a-b5fc-c5e4d5a83367",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c3cf7ee-7ddc-4fd1-9e6c-0b9ff9a53513",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
